/**
 * @file Encrypt.h
 * @author Laksh Aggarwal (aggarwallaksh54@gmail.com)
 * @brief Just a simple Algorithm to encrypt data.
 * @version 0.1
 * @date 2022-07-31
 */
#include "Key/Key.h"
#include <stdlib.h>

// #define MAX_ITERATIONS 9
// #define MIN_ITERATIONS 3

// #define MIN_ROW_CLMN_SIZE 3
// #define MAX_ROW_CLMN_SIZE 10

/**
 * @brief Encrypts the data using the key k. Key can be generated by generate_key method.
 * @param k 
 * @param data 
 * @param size 
 * @return bool
 */
bool iencrypt(key k, void *data, unsigned long size);

/**
 * @brief Decrypts the data using the key k.
 * @param k 
 * @param data 
 * @param size 
 * @return bool
 */
bool idecrypt(key k, void *data, unsigned long size);